export const AUDIO_CONSTANTS = {
  SAMPLE_RATE: 16_000,
  FFT_SIZE: 2048,
  HOP_LENGTH: 1024,
  PITCH_VARIANCE_MIN: 0.05,
  PITCH_VARIANCE_MAX: 0.5,
  JITTER_THRESHOLD: 0.02,
  ENERGY_VAR_THRESHOLD: 0.1,
  PAUSE_RMS_THRESHOLD: 0.01,
  WINDOW_SIZE_SECONDS: 5.0,
  PITCH_CONFIDENCE_THRESHOLD: 0.5,
  F0_MIN_HZ: 50,
  F0_MAX_HZ: 500,
  ROUND_DECIMALS: 4,
  YIELD_EVERY_N_FRAMES: 12,
} as const;

export const AUDIO_PIPELINE_VERSION = {
  pipeline: 'audio-device-v1',
  formula: 'frontend-formulas-2026-04-06',
} as const;
